name: Upload BrowserStack Test Suite

on:
  workflow_dispatch:

jobs:
  upload_browserstack_testsuite:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: kartik_c4hHwJ
      BROWSERSTACK_ACCESS_KEY: vY6uRQ4t2gEHXPmE9UJL

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Zip the browserstack Folder
        run: |
          cd automation/Headlamp
          echo "Zipping automation/Headlamp/browserstack..."
          zip -r browserstack.zip browserstack
          mv browserstack.zip $GITHUB_WORKSPACE/
          echo "browserstack.zip created in $GITHUB_WORKSPACE"


      - name: Upload Test Suite to BrowserStack
        id: upload_suite
        run: |
          echo "Uploading test suite to BrowserStack..."
          response=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" \
            -X POST "https://api-cloud.browserstack.com/app-automate/maestro/v2/test-suite" \
            -F "file=@${GITHUB_WORKSPACE}/browserstack.zip" \
            -F "custom_id=Automation_TestSuite_${{ github.run_id }}" \
            -s -w "\n%{http_code}")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "Response HTTP code: $http_code"
          echo "Response body: $body"

          if [[ "$http_code" == "200" ]]; then
            test_suite_url=$(echo "$body" | jq -r '.test_suite_url // empty')
            echo "Upload successful. Test suite URL: $test_suite_url"
            echo "UPLOAD_SUCCESS=true" >> $GITHUB_ENV
            echo "TEST_SUITE_URL=$test_suite_url" >> $GITHUB_ENV
          else
            echo "Upload failed."
            echo "UPLOAD_SUCCESS=false" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "${{ env.UPLOAD_SUCCESS == 'true' && '✅ BrowserStack Test Suite uploaded successfully!' || '❌ BrowserStack Test Suite upload failed.' }}\nTest Suite URL: ${{ env.TEST_SUITE_URL != '' && env.TEST_SUITE_URL || 'N/A' }}\nView Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEST_PIPELINE_SLACK_WEBHOOK_URL }}
