name: Upload  Test Suite

on:
  workflow_dispatch:

jobs:
  upload-testsuite:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: kartikgupta_bpv503
      BROWSERSTACK_ACCESS_KEY: qQgg7fV2kkwKs3JJqdbS

    steps:
      - name: Checkout Automation Repository
        uses: actions/checkout@v4

      - name: Debug Current Directory
        run: |
          echo "PWD: $(pwd)"
          echo "Root Contents:"
          ls -la
          echo "automation Folder Contents:"
          ls -la automation

      - name: Zip the BrowserStack Folder
        run: |
          echo "Zipping automation/Headlamp/browserstack..."
          zip -r browserstack.zip automation/Headlamp/browserstack
          echo "Zip file created:"
          ls -lh browserstack.zip

      - name: Upload Test Suite to BrowserStack
        id: upload_testsuite
        run: |
          echo "Uploading browserstack.zip to BrowserStack..."
          RESPONSE=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" \
            -X POST "https://api-cloud.browserstack.com/app-automate/maestro/v2/test-suite" \
            -F "file=@browserstack.zip")
          
          echo "Response from BrowserStack:"
          echo "$RESPONSE"
          
          TEST_SUITE_URL=$(echo "$RESPONSE" | jq -r '.test_suite_url // empty')

          if [ -z "$TEST_SUITE_URL" ]; then
            echo "Upload failed or test_suite_url not found."
            echo "TEST_UPLOAD_STATUS=fail" >> $GITHUB_ENV
          else
            echo "Test Suite URL: $TEST_SUITE_URL"
            echo "TEST_SUITE_URL=$TEST_SUITE_URL" >> $GITHUB_ENV
            echo "TEST_UPLOAD_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification - Success
        if: env.TEST_UPLOAD_STATUS == 'success'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ BrowserStack Test Suite uploaded successfully!\nTest Suite URL: ${{ env.TEST_SUITE_URL }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEST_PIPELINE_SLACK_WEBHOOK_URL }}

      - name: Send Slack Notification - Failure
        if: env.TEST_UPLOAD_STATUS != 'success'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ BrowserStack Test Suite upload failed!\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEST_PIPELINE_SLACK_WEBHOOK_URL }}
